### **Why Do We Need Arrays When We Have Lists?**

1. **Memory Efficiency:**
    - Arrays are more memory-efficient compared to lists. They store elements of the same data type, whereas lists can store elements of mixed types.

        
2. **Type Safety:**
    - Arrays enforce type consistency, meaning all elements must be of the same data type. This reduces the chances of errors when performing mathematical or logical operations.

        
3. **Performance:**
    - For numerical computations, arrays are faster because they avoid the overhead of type checking for each element during operations.

        
4. **Specialized Use Cases:**
    - Arrays are better suited for numerical and scientific computations where all elements share the same type.
    - Libraries like **NumPy** use arrays as their core data structure for matrix operations, numerical integration, and more.

        
5. **List Flexibility vs. Array Specialization:**
    - Lists are more flexible and can store elements of different types.
    - Arrays are specialized for uniform data and are more efficient in computational and memory-heavy tasks.

### **Key Differences Between List and Array**

| **Feature** | **List** | **Array** |
| --- | --- | --- |
| **Type of Data** | Can store mixed data types | Stores data of the same type only |
| **Memory Usage** | More memory overhead | Memory efficient |
| **Performance** | Slower for numerical computations | Faster for numerical computations |
| **Operations** | General-purpose operations | Specialized for numerical operations |
| **Library Dependency** | Built-in | Requires `array` or external libraries like NumPy |

---

### **When to Use Lists**:

1. **Flexibility**: Lists can store elements of **different data types**.
2. **Built-in Methods**: Lists have many built-in methods like `append()`, `pop()`, `sort()`, etc.
3. **Dynamic Sizing**: Lists automatically resize as elements are added or removed.
4. **General Use**: Ideal for most use cases like storing collections of items, stacks, queues, etc.

---

### **When to Use Arrays**:

1. **Performance**: Arrays are faster for **numeric computations** (use libraries like `NumPy`).
2. **Memory Efficiency**: Arrays use less memory for **homogeneous data** (e.g., all integers or floats).
3. **Mathematical Operations**: Arrays support vectorized operations (e.g., element-wise addition).
4. **Specialized Use**: Ideal for scientific computing, machine learning, and large datasets.

### **Explanation of Key Operations**

1. **Access (`O(1)`)**:
    - Python lists are implemented as dynamic arrays, so accessing an element by index is a constant-time operation.
2. **Append (`O(1)`)**:
    - Appending to the end of the list is amortized `O(1)` because Python overallocates memory for the list to reduce the frequency of resizing.
3. **Insert and Delete (`O(n)`)**:
    - Inserting or deleting an element at a specific index requires shifting all subsequent elements, which takes linear time.
4. **Search (`O(n)`)**:
    - Searching for an element by value requires iterating through the list in the worst case.
5. **Sort (`O(n log n)`)**:
    - Python's built-in sorting algorithm (Timsort) has a time complexity of `O(n log n)`.
6. **Slice (`O(k)`)**:
    - Slicing a list creates a new list with the specified elements, so the time complexity depends on the size of the slice.
7. **Extend (`O(k)`)**:
    - Extending a list with another iterable takes time proportional to the length of the iterable being added.

# Arrays

# creation

In [1]:
import array

arr_int=array.array('i',[1,2,3,4,5])


In [2]:
arr_int

array('i', [1, 2, 3, 4, 5])

In [3]:
type(arr_int)

array.array

In [4]:
import numpy as np

In [5]:
arr_1d=np.array([1,2,3,4,5])

In [47]:
type(arr_1d)

numpy.ndarray

In [15]:
l = [1,2,3,4,4]
arr_1d=np.array(l)
arr_1d

array([1, 2, 3, 4, 4])

In [13]:
type(l)

list

In [6]:
arr_2d=np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [7]:
type(arr_2d)

numpy.ndarray

In [8]:
arr_2d

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

# traversing

In [17]:
arr_1d

array([1, 2, 3, 4, 4])

In [16]:
for i in arr_1d:
    print(i[4])


IndexError: invalid index to scalar variable.

In [18]:
for i ,ele in enumerate(arr_1d):
    print(i,ele)


0 1
1 2
2 3
3 4
4 4


# Access

In [1]:
import numpy as np
l = [1,2,3,4,4]
arr_1d=np.array(l)

In [20]:
arr_1d[3]

4

In [26]:
arr_2d

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [ ]:
print(arr_2d[0][4])
print(arr_2d[1][3])


5
7


In [21]:
import array
arr1 = array.array('i', [1, 2, 3, 4, 5])

print(arr1[2]) 


3


In [22]:
print(arr1[4]) 

5


In [23]:
print(arr1[0:5:-2]) 

array('i')


In [ ]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) ## two 2d array are nothing but 3d array
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
print(arr_3d[0][1])
print(arr_3d[1][0])

[4 5 6]
[7 8 9]


In [37]:
print(arr_3d[0][0][2])
print(arr_3d[0][1][1])
print(arr_3d[1][1][0])
print(arr_3d[1][0][2])

3
5
10
9


# insertion 

In [38]:
arr_3d.insert(1,[2])

AttributeError: 'numpy.ndarray' object has no attribute 'insert'


### The syntax for numpy.insert() is:

############syntax##########
numpy.insert(arr, obj, values, axis=None)

arr: The input array.

obj: The index before which the values are inserted.

values: The values to insert into the array.

axis: The axis along which to insert the values. If axis is not provided, the array is flattened before insertion

In [47]:
print(arr_3d.shape)
print(arr_3d.size)

(2, 2, 3)
12


In [43]:
new_obj=np.array([[[13,14,15],[16.0,17.1,18]]])
new=np.insert(arr_3d,1,new_obj,axis=0)
new

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
new_obj=np.array([[[13,14,15],[16.0,17.1,18]]])## allow folat as integer
new=np.insert(arr_3d,1,new_obj,axis=1)
new

array([[[ 1,  2,  3],
        [13, 14, 15],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [16, 17, 18],
        [10, 11, 12]]])

In [42]:
arr1

array('i', [1, 2, 99, 3, 4, 5])

In [24]:
arr1.insert(2,99)

In [25]:
arr1

array('i', [1, 2, 99, 3, 4, 5])

In [48]:
arr1.append(5)
arr1

array('i', [1, 2, 99, 3, 4, 5, 5])

In [49]:
arr1.extend([34,5,7])
arr1

array('i', [1, 2, 99, 3, 4, 5, 5, 34, 5, 7])

In [51]:
arr1[5] = 2343
arr1


array('i', [1, 2, 99, 3, 4, 2343, 5, 34, 5, 7])

In [52]:
arr1.count(99)

1

In [53]:
len(arr1)

10

In [54]:
arr1.sort()

AttributeError: 'array.array' object has no attribute 'sort'

In [55]:
sorted(arr1, reverse=True)

[2343, 99, 34, 7, 5, 5, 4, 3, 2, 1]

In [29]:
arr1

array('i', [1, 2, 99, 99, 99, 2343, 4, 5, 4, 34, 5, 7])

In [56]:
arr1.reverse()

In [57]:
arr1

array('i', [7, 5, 34, 5, 2343, 4, 3, 99, 2, 1])

In [32]:
arr1[::-1]

array('i', [1, 2, 99, 99, 99, 2343, 4, 5, 4, 34, 5, 7])

In [59]:
print(991 in arr1)
print(99 in arr1)

False
True


In [60]:
arr1*2

array('i', [7, 5, 34, 5, 2343, 4, 3, 99, 2, 1, 7, 5, 34, 5, 2343, 4, 3, 99, 2, 1])

### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [63]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype='S')
arr.dtype

dtype('S1')

## in numpy copy & view 
### copy--# donot make any changes
### view --## do make changes

In [67]:
arr1=np.array([1,2,3,4,5])
x=np.copy(arr1)
arr1[2]=99
print(x)
print(arr1)

[1 2 3 4 5]
[ 1  2 99  4  5]


In [70]:
x=arr1.view()
arr1[2]=99
print(x)
print(arr1)

[ 1  2 99  4  5]
[ 1  2 99  4  5]


### shape

In [72]:
arr_shape=np.array([23,3,2,4,5,6],ndmin=4)
print(arr_shape)
print(arr_shape.shape)

[[[[23  3  2  4  5  6]]]]
(1, 1, 1, 6)


In [85]:
# Print the dtype of array
my_array = np.array([1,2,3,4,5])
print(my_array.dtype)

int32


This means:(1, 1, 1, 6)

The first dimension has size 1.

The second dimension has size 1.

The third dimension has size 1.

The fourth (innermost) dimension has size 6, corresponding to the 6 elements in the original list.


## reshape

Reshape From 1-D to 2-D

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
arr_reshpe=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr_reshpe.reshape(4,3)
print(new_arr)
print(new_arr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## astype

In [86]:
# Create an array
arravali = np.array([2,3,4])
print(arravali)
print(arravali.dtype)

# Change the datatype of the array to float
arravali_ = arravali.astype('float64')
print(arravali_)
print(arravali_.dtype)

[2 3 4]
int32
[2. 3. 4.]
float64


##### 1-D to 3D array

In [77]:
new_arr1=arr_reshpe.reshape(2,3,2)
print(new_arr1)
print(new_arr1.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [78]:
new_arr1=arr_reshpe.reshape(3,4)
print(new_arr1)
print(new_arr1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [84]:
alma_array = np.array([[[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]])
# print(alma_array)
print(alma_array.shape)

(4, 2, 3)


## flatening array

In [80]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


## iterating 

In [81]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [83]:
arr_iter=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in arr_iter:
    for y in x:
        print(y)
        for z in y:
            print(z)

[1 2]
1
2
[3 4]
3
4
[5 6]
5
6
[7 8]
7
8


## joins

### concatenation

In [87]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10,11])
new_arr=np.concatenate((arr1,arr2))
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Join two 2-D arrays along rows (axis=1):

In [89]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
new_arr=np.concatenate((arr1,arr2))
new_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## stack

In [90]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [92]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### 1. **Find Duplicates in an Array**

**Problem**: Given an array, find all the elements that appear more than once.

**Approach**:

- Use a set to keep track of elements that have been seen before. If you encounter an element that is already in the set, it's a duplicate.

2. **Find Missing Number in Array**
    - **Problem**: Given an array of n-1 integers in the range of 1 to n, find the missing number.

### 3. **Rotate an Array**

**Problem**: Rotate an array by `k` positions to the right.

**Approach**:

- Use array slicing to achieve the rotation.

### 4. **Merge Two Sorted Arrays**

**Problem**: Given two sorted arrays, merge them into a single sorted array.

**Approach**:

- Use two pointers to iterate through both arrays and add the smaller element to the result array.

### 5. **Find Intersection of Two Arrays**

**Problem**: Find the common elements (intersection) between two arrays.

**Approach**:

- Convert both arrays to sets and find their intersection.

### **6. Move Zeros to the Beginning**

- **Problem**: Move all zeros in an array to the beginning without changing the order of non-zero elements.